language: python
python:
  - "3.8"
# command to install dependencies
install: 
  - pip --version
  - pip install coverage
# command to run tests
script:
  - coverage run -m pytest
# After success
after_success:
  - coverage report